<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-06-03 23:49:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\EscuelaBundle\Entity\Alumno
 *
 * @ORM\Entity()
 * @ORM\Table(name="Alumno")
 */
class Alumno
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $FechaNacimiento;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Diagnostico;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Observaciones;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Foto;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoResponsable", mappedBy="alumno")
     * @ORM\JoinColumn(name="id", referencedColumnName="Alumno_id")
     */
    protected $alumnoResponsables;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoSalon", mappedBy="alumno")
     * @ORM\JoinColumn(name="id", referencedColumnName="Alumno_id")
     */
    protected $alumnoSalons;

    public function __construct()
    {
        $this->alumnoResponsables = new ArrayCollection();
        $this->alumnoSalons = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of FechaNacimiento.
     *
     * @param \DateTime $FechaNacimiento
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function setFechaNacimiento($FechaNacimiento)
    {
        $this->FechaNacimiento = $FechaNacimiento;

        return $this;
    }

    /**
     * Get the value of FechaNacimiento.
     *
     * @return \DateTime
     */
    public function getFechaNacimiento()
    {
        return $this->FechaNacimiento;
    }

    /**
     * Set the value of Diagnostico.
     *
     * @param string $Diagnostico
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function setDiagnostico($Diagnostico)
    {
        $this->Diagnostico = $Diagnostico;

        return $this;
    }

    /**
     * Get the value of Diagnostico.
     *
     * @return string
     */
    public function getDiagnostico()
    {
        return $this->Diagnostico;
    }

    /**
     * Set the value of Observaciones.
     *
     * @param string $Observaciones
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function setObservaciones($Observaciones)
    {
        $this->Observaciones = $Observaciones;

        return $this;
    }

    /**
     * Get the value of Observaciones.
     *
     * @return string
     */
    public function getObservaciones()
    {
        return $this->Observaciones;
    }

    /**
     * Set the value of Foto.
     *
     * @param string $Foto
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function setFoto($Foto)
    {
        $this->Foto = $Foto;

        return $this;
    }

    /**
     * Get the value of Foto.
     *
     * @return string
     */
    public function getFoto()
    {
        return $this->Foto;
    }

    /**
     * Add AlumnoResponsable entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\AlumnoResponsable $alumnoResponsable
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function addAlumnoResponsable(AlumnoResponsable $alumnoResponsable)
    {
        $this->alumnoResponsables[] = $alumnoResponsable;

        return $this;
    }

    /**
     * Remove AlumnoResponsable entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\AlumnoResponsable $alumnoResponsable
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function removeAlumnoResponsable(AlumnoResponsable $alumnoResponsable)
    {
        $this->alumnoResponsables->removeElement($alumnoResponsable);

        return $this;
    }

    /**
     * Get AlumnoResponsable entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoResponsables()
    {
        return $this->alumnoResponsables;
    }

    /**
     * Add AlumnoSalon entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\AlumnoSalon $alumnoSalon
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function addAlumnoSalon(AlumnoSalon $alumnoSalon)
    {
        $this->alumnoSalons[] = $alumnoSalon;

        return $this;
    }

    /**
     * Remove AlumnoSalon entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\AlumnoSalon $alumnoSalon
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function removeAlumnoSalon(AlumnoSalon $alumnoSalon)
    {
        $this->alumnoSalons->removeElement($alumnoSalon);

        return $this;
    }

    /**
     * Get AlumnoSalon entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoSalons()
    {
        return $this->alumnoSalons;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'FechaNacimiento', 'Diagnostico', 'Observaciones', 'Foto');
    }
}