<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-31 18:07:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\EscuelaBundle\Entity\AlumnoResponsable
 *
 * @ORM\Entity()
 * @ORM\Table(name="AlumnoResponsable", indexes={@ORM\Index(name="fk_AlumnoResponsable_Alumno1_idx", columns={"Alumno_id"}), @ORM\Index(name="fk_AlumnoResponsable_Responsable1_idx", columns={"Responsable_id"})})
 */
class AlumnoResponsable
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Alumno_id;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Responsable_id;

    /**
     * @ORM\ManyToOne(targetEntity="Alumno", inversedBy="alumnoResponsables")
     * @ORM\JoinColumn(name="Alumno_id", referencedColumnName="id")
     */
    protected $alumno;

    /**
     * @ORM\ManyToOne(targetEntity="Responsable", inversedBy="alumnoResponsables")
     * @ORM\JoinColumn(name="Responsable_id", referencedColumnName="id")
     */
    protected $responsable;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\AlumnoResponsable
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Alumno_id.
     *
     * @param integer $Alumno_id
     * @return \Umg\EscuelaBundle\Entity\AlumnoResponsable
     */
    public function setAlumnoId($Alumno_id)
    {
        $this->Alumno_id = $Alumno_id;

        return $this;
    }

    /**
     * Get the value of Alumno_id.
     *
     * @return integer
     */
    public function getAlumnoId()
    {
        return $this->Alumno_id;
    }

    /**
     * Set the value of Responsable_id.
     *
     * @param integer $Responsable_id
     * @return \Umg\EscuelaBundle\Entity\AlumnoResponsable
     */
    public function setResponsableId($Responsable_id)
    {
        $this->Responsable_id = $Responsable_id;

        return $this;
    }

    /**
     * Get the value of Responsable_id.
     *
     * @return integer
     */
    public function getResponsableId()
    {
        return $this->Responsable_id;
    }

    /**
     * Set Alumno entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Alumno $alumno
     * @return \Umg\EscuelaBundle\Entity\AlumnoResponsable
     */
    public function setAlumno(Alumno $alumno = null)
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * Get Alumno entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Alumno
     */
    public function getAlumno()
    {
        return $this->alumno;
    }

    /**
     * Set Responsable entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Responsable $responsable
     * @return \Umg\EscuelaBundle\Entity\AlumnoResponsable
     */
    public function setResponsable(Responsable $responsable = null)
    {
        $this->responsable = $responsable;

        return $this;
    }

    /**
     * Get Responsable entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Responsable
     */
    public function getResponsable()
    {
        return $this->responsable;
    }

    public function __sleep()
    {
        return array('id', 'Alumno_id', 'Responsable_id');
    }
}