<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-06-04 15:40:29.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\EscuelaBundle\Entity\Articulo
 *
 * @ORM\Entity()
 * @ORM\Table(name="Articulo")
 */
class Articulo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Articulo;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\Articulo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\EscuelaBundle\Entity\Articulo
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Articulo.
     *
     * @param string $Articulo
     * @return \Umg\EscuelaBundle\Entity\Articulo
     */
    public function setArticulo($Articulo)
    {
        $this->Articulo = $Articulo;

        return $this;
    }

    /**
     * Get the value of Articulo.
     *
     * @return string
     */
    public function getArticulo()
    {
        return $this->Articulo;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Articulo');
    }
}