<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-31 18:07:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\EscuelaBundle\Entity\Categorium
 *
 * @ORM\Entity()
 * @ORM\Table(name="Categoria")
 */
class Categorium
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=155, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\OneToMany(targetEntity="Insumo", mappedBy="categorium")
     * @ORM\JoinColumn(name="id", referencedColumnName="Categoria_id")
     */
    protected $insumos;

    public function __construct()
    {
        $this->insumos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\Categorium
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\EscuelaBundle\Entity\Categorium
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Add Insumo entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\Insumo $insumo
     * @return \Umg\EscuelaBundle\Entity\Categorium
     */
    public function addInsumo(Insumo $insumo)
    {
        $this->insumos[] = $insumo;

        return $this;
    }

    /**
     * Remove Insumo entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\Insumo $insumo
     * @return \Umg\EscuelaBundle\Entity\Categorium
     */
    public function removeInsumo(Insumo $insumo)
    {
        $this->insumos->removeElement($insumo);

        return $this;
    }

    /**
     * Get Insumo entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getInsumos()
    {
        return $this->insumos;
    }

    public function __sleep()
    {
        return array('id', 'Nombre');
    }

    public function __toString()
    {
        return $this->Nombre;
    }
}