<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-31 18:07:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Umg\EscuelaBundle\Entity\HistorialInsumo
 *
 * @ORM\Entity()
 * @ORM\Table(name="HistorialInsumo", indexes={@ORM\Index(name="fk_HistorialInsumo_Insumo1_idx", columns={"Insumo_id"}), @ORM\Index(name="fk_HistorialInsumo_InsumoPersonal1_idx", columns={"InsumoPersonal_id"}), @ORM\Index(name="fk_HistorialInsumo_Usuario1_idx", columns={"Usuario_id"})})
 */
class HistorialInsumo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $FechaHora;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $Entrada;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $Salida;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Insumo_id;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $InsumoPersonal_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Usuario_id;

    /**
     * @ORM\ManyToOne(targetEntity="Insumo", inversedBy="historialInsumos")
     * @ORM\JoinColumn(name="Insumo_id", referencedColumnName="id")
     */
    protected $insumo;

    /**
     * @ORM\ManyToOne(targetEntity="InsumoPersonal", inversedBy="historialInsumos")
     * @ORM\JoinColumn(name="InsumoPersonal_id", referencedColumnName="id")
     */
    protected $insumoPersonal;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="historialInsumos")
     * @ORM\JoinColumn(name="Usuario_id", referencedColumnName="id")
     */
    protected $usuario;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of FechaHora.
     *
     * @param \DateTime $FechaHora
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setFechaHora($FechaHora)
    {
        $this->FechaHora = $FechaHora;

        return $this;
    }

    /**
     * Get the value of FechaHora.
     *
     * @return \DateTime
     */
    public function getFechaHora()
    {
        return $this->FechaHora;
    }

    /**
     * Set the value of Entrada.
     *
     * @param float $Entrada
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setEntrada($Entrada)
    {
        $this->Entrada = $Entrada;

        return $this;
    }

    /**
     * Get the value of Entrada.
     *
     * @return float
     */
    public function getEntrada()
    {
        return $this->Entrada;
    }

    /**
     * Set the value of Salida.
     *
     * @param float $Salida
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setSalida($Salida)
    {
        $this->Salida = $Salida;

        return $this;
    }

    /**
     * Get the value of Salida.
     *
     * @return float
     */
    public function getSalida()
    {
        return $this->Salida;
    }

    /**
     * Set the value of Insumo_id.
     *
     * @param integer $Insumo_id
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setInsumoId($Insumo_id)
    {
        $this->Insumo_id = $Insumo_id;

        return $this;
    }

    /**
     * Get the value of Insumo_id.
     *
     * @return integer
     */
    public function getInsumoId()
    {
        return $this->Insumo_id;
    }

    /**
     * Set the value of InsumoPersonal_id.
     *
     * @param integer $InsumoPersonal_id
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setInsumoPersonalId($InsumoPersonal_id)
    {
        $this->InsumoPersonal_id = $InsumoPersonal_id;

        return $this;
    }

    /**
     * Get the value of InsumoPersonal_id.
     *
     * @return integer
     */
    public function getInsumoPersonalId()
    {
        return $this->InsumoPersonal_id;
    }

    /**
     * Set the value of Usuario_id.
     *
     * @param integer $Usuario_id
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setUsuarioId($Usuario_id)
    {
        $this->Usuario_id = $Usuario_id;

        return $this;
    }

    /**
     * Get the value of Usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->Usuario_id;
    }

    /**
     * Set Insumo entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Insumo $insumo
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setInsumo(Insumo $insumo = null)
    {
        $this->insumo = $insumo;

        return $this;
    }

    /**
     * Get Insumo entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function getInsumo()
    {
        return $this->insumo;
    }

    /**
     * Set InsumoPersonal entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\InsumoPersonal $insumoPersonal
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setInsumoPersonal(InsumoPersonal $insumoPersonal = null)
    {
        $this->insumoPersonal = $insumoPersonal;

        return $this;
    }

    /**
     * Get InsumoPersonal entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function getInsumoPersonal()
    {
        return $this->insumoPersonal;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Usuario $usuario
     * @return \Umg\EscuelaBundle\Entity\HistorialInsumo
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    public function __sleep()
    {
        return array('id', 'FechaHora', 'Entrada', 'Salida', 'Insumo_id', 'InsumoPersonal_id', 'Usuario_id');
    }
}