<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-31 18:07:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\EscuelaBundle\Entity\Insumo
 *
 * @ORM\Entity()
 * @ORM\Table(name="Insumo", indexes={@ORM\Index(name="fk_Insumo_Fuente_idx", columns={"Fuente_id"}), @ORM\Index(name="fk_Insumo_Categoria1_idx", columns={"Categoria_id"})})
 */
class Insumo
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Codigo;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $Cantidad;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $CantidadDisponible;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $Retornable;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Fuente_id;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Categoria_id;

    /**
     * @ORM\OneToMany(targetEntity="HistorialInsumo", mappedBy="insumo")
     * @ORM\JoinColumn(name="id", referencedColumnName="Insumo_id")
     */
    protected $historialInsumos;

    /**
     * @ORM\OneToMany(targetEntity="InsumoPersonal", mappedBy="insumo")
     * @ORM\JoinColumn(name="id", referencedColumnName="Insumo_id")
     */
    protected $insumoPersonals;

    /**
     * @ORM\ManyToOne(targetEntity="Fuente", inversedBy="insumos")
     * @ORM\JoinColumn(name="Fuente_id", referencedColumnName="id")
     */
    protected $fuente;

    /**
     * @ORM\ManyToOne(targetEntity="Categorium", inversedBy="insumos")
     * @ORM\JoinColumn(name="Categoria_id", referencedColumnName="id")
     */
    protected $categorium;

    public function __construct()
    {
        $this->historialInsumos = new ArrayCollection();
        $this->insumoPersonals = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Codigo.
     *
     * @param string $Codigo
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setCodigo($Codigo)
    {
        $this->Codigo = $Codigo;

        return $this;
    }

    /**
     * Get the value of Codigo.
     *
     * @return string
     */
    public function getCodigo()
    {
        return $this->Codigo;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Cantidad.
     *
     * @param float $Cantidad
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setCantidad($Cantidad)
    {
        $this->Cantidad = $Cantidad;

        return $this;
    }

    /**
     * Get the value of Cantidad.
     *
     * @return float
     */
    public function getCantidad()
    {
        return $this->Cantidad;
    }

    /**
     * Set the value of CantidadDisponible.
     *
     * @param float $CantidadDisponible
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setCantidadDisponible($CantidadDisponible)
    {
        $this->CantidadDisponible = $CantidadDisponible;

        return $this;
    }

    /**
     * Get the value of CantidadDisponible.
     *
     * @return float
     */
    public function getCantidadDisponible()
    {
        return $this->CantidadDisponible;
    }

    /**
     * Set the value of Retornable.
     *
     * @param boolean $Retornable
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setRetornable($Retornable)
    {
        $this->Retornable = $Retornable;

        return $this;
    }

    /**
     * Get the value of Retornable.
     *
     * @return boolean
     */
    public function getRetornable()
    {
        return $this->Retornable;
    }

    /**
     * Set the value of Fuente_id.
     *
     * @param integer $Fuente_id
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setFuenteId($Fuente_id)
    {
        $this->Fuente_id = $Fuente_id;

        return $this;
    }

    /**
     * Get the value of Fuente_id.
     *
     * @return integer
     */
    public function getFuenteId()
    {
        return $this->Fuente_id;
    }

    /**
     * Set the value of Categoria_id.
     *
     * @param integer $Categoria_id
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setCategoriaId($Categoria_id)
    {
        $this->Categoria_id = $Categoria_id;

        return $this;
    }

    /**
     * Get the value of Categoria_id.
     *
     * @return integer
     */
    public function getCategoriaId()
    {
        return $this->Categoria_id;
    }

    /**
     * Add HistorialInsumo entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\HistorialInsumo $historialInsumo
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function addHistorialInsumo(HistorialInsumo $historialInsumo)
    {
        $this->historialInsumos[] = $historialInsumo;

        return $this;
    }

    /**
     * Remove HistorialInsumo entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\HistorialInsumo $historialInsumo
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function removeHistorialInsumo(HistorialInsumo $historialInsumo)
    {
        $this->historialInsumos->removeElement($historialInsumo);

        return $this;
    }

    /**
     * Get HistorialInsumo entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getHistorialInsumos()
    {
        return $this->historialInsumos;
    }

    /**
     * Add InsumoPersonal entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\InsumoPersonal $insumoPersonal
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function addInsumoPersonal(InsumoPersonal $insumoPersonal)
    {
        $this->insumoPersonals[] = $insumoPersonal;

        return $this;
    }

    /**
     * Remove InsumoPersonal entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\InsumoPersonal $insumoPersonal
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function removeInsumoPersonal(InsumoPersonal $insumoPersonal)
    {
        $this->insumoPersonals->removeElement($insumoPersonal);

        return $this;
    }

    /**
     * Get InsumoPersonal entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getInsumoPersonals()
    {
        return $this->insumoPersonals;
    }

    /**
     * Set Fuente entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Fuente $fuente
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setFuente(Fuente $fuente = null)
    {
        $this->fuente = $fuente;

        return $this;
    }

    /**
     * Get Fuente entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Fuente
     */
    public function getFuente()
    {
        return $this->fuente;
    }

    /**
     * Set Categorium entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Categorium $categorium
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function setCategorium(Categorium $categorium = null)
    {
        $this->categorium = $categorium;

        return $this;
    }

    /**
     * Get Categorium entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Categorium
     */
    public function getCategorium()
    {
        return $this->categorium;
    }

    public function __sleep()
    {
        return array('id', 'Codigo', 'Nombre', 'Cantidad', 'CantidadDisponible', 'Retornable', 'Fuente_id', 'Categoria_id');
    }
}