<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-31 18:07:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\EscuelaBundle\Entity\InsumoPersonal
 *
 * @ORM\Entity()
 * @ORM\Table(name="InsumoPersonal", indexes={@ORM\Index(name="fk_InsumoPersonal_Insumo1_idx", columns={"Insumo_id"}), @ORM\Index(name="fk_InsumoPersonal_Personal1_idx", columns={"Personal_id"})})
 */
class InsumoPersonal
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $Cantidad;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $Retornado;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Insumo_id;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Personal_id;

    /**
     * @ORM\OneToMany(targetEntity="HistorialInsumo", mappedBy="insumoPersonal")
     * @ORM\JoinColumn(name="id", referencedColumnName="InsumoPersonal_id")
     */
    protected $historialInsumos;

    /**
     * @ORM\ManyToOne(targetEntity="Insumo", inversedBy="insumoPersonals")
     * @ORM\JoinColumn(name="Insumo_id", referencedColumnName="id")
     */
    protected $insumo;

    /**
     * @ORM\ManyToOne(targetEntity="Personal", inversedBy="insumoPersonals")
     * @ORM\JoinColumn(name="Personal_id", referencedColumnName="id")
     */
    protected $personal;

    public function __construct()
    {
        $this->historialInsumos = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Cantidad.
     *
     * @param float $Cantidad
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setCantidad($Cantidad)
    {
        $this->Cantidad = $Cantidad;

        return $this;
    }

    /**
     * Get the value of Cantidad.
     *
     * @return float
     */
    public function getCantidad()
    {
        return $this->Cantidad;
    }

    /**
     * Set the value of Retornado.
     *
     * @param boolean $Retornado
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setRetornado($Retornado)
    {
        $this->Retornado = $Retornado;

        return $this;
    }

    /**
     * Get the value of Retornado.
     *
     * @return boolean
     */
    public function getRetornado()
    {
        return $this->Retornado;
    }

    /**
     * Set the value of Insumo_id.
     *
     * @param integer $Insumo_id
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setInsumoId($Insumo_id)
    {
        $this->Insumo_id = $Insumo_id;

        return $this;
    }

    /**
     * Get the value of Insumo_id.
     *
     * @return integer
     */
    public function getInsumoId()
    {
        return $this->Insumo_id;
    }

    /**
     * Set the value of Personal_id.
     *
     * @param integer $Personal_id
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setPersonalId($Personal_id)
    {
        $this->Personal_id = $Personal_id;

        return $this;
    }

    /**
     * Get the value of Personal_id.
     *
     * @return integer
     */
    public function getPersonalId()
    {
        return $this->Personal_id;
    }

    /**
     * Add HistorialInsumo entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\HistorialInsumo $historialInsumo
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function addHistorialInsumo(HistorialInsumo $historialInsumo)
    {
        $this->historialInsumos[] = $historialInsumo;

        return $this;
    }

    /**
     * Remove HistorialInsumo entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\HistorialInsumo $historialInsumo
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function removeHistorialInsumo(HistorialInsumo $historialInsumo)
    {
        $this->historialInsumos->removeElement($historialInsumo);

        return $this;
    }

    /**
     * Get HistorialInsumo entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getHistorialInsumos()
    {
        return $this->historialInsumos;
    }

    /**
     * Set Insumo entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Insumo $insumo
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setInsumo(Insumo $insumo = null)
    {
        $this->insumo = $insumo;

        return $this;
    }

    /**
     * Get Insumo entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Insumo
     */
    public function getInsumo()
    {
        return $this->insumo;
    }

    /**
     * Set Personal entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Personal $personal
     * @return \Umg\EscuelaBundle\Entity\InsumoPersonal
     */
    public function setPersonal(Personal $personal = null)
    {
        $this->personal = $personal;

        return $this;
    }

    /**
     * Get Personal entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function getPersonal()
    {
        return $this->personal;
    }

    public function __sleep()
    {
        return array('id', 'Cantidad', 'Retornado', 'Insumo_id', 'Personal_id');
    }
}