<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-06-03 23:49:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\EscuelaBundle\Entity\Personal
 *
 * @ORM\Entity()
 * @ORM\Table(name="Personal", indexes={@ORM\Index(name="fk_Personal_Usuario1_idx", columns={"Usuario_id"})})
 */
class Personal
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Documento;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Logros;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Observacion;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $Foto;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Usuario_id;

    /**
     * @ORM\OneToMany(targetEntity="InsumoPersonal", mappedBy="personal")
     * @ORM\JoinColumn(name="id", referencedColumnName="Personal_id")
     */
    protected $insumoPersonals;

    /**
     * @ORM\OneToMany(targetEntity="Salon", mappedBy="personal")
     * @ORM\JoinColumn(name="id", referencedColumnName="Personal_id")
     */
    protected $salons;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="personals")
     * @ORM\JoinColumn(name="Usuario_id", referencedColumnName="id", nullable=true)
     */
    protected $usuario;

    public function __construct()
    {
        $this->insumoPersonals = new ArrayCollection();
        $this->salons = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Documento.
     *
     * @param string $Documento
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setDocumento($Documento)
    {
        $this->Documento = $Documento;

        return $this;
    }

    /**
     * Get the value of Documento.
     *
     * @return string
     */
    public function getDocumento()
    {
        return $this->Documento;
    }

    /**
     * Set the value of Logros.
     *
     * @param string $Logros
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setLogros($Logros)
    {
        $this->Logros = $Logros;

        return $this;
    }

    /**
     * Get the value of Logros.
     *
     * @return string
     */
    public function getLogros()
    {
        return $this->Logros;
    }

    /**
     * Set the value of Observacion.
     *
     * @param string $Observacion
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setObservacion($Observacion)
    {
        $this->Observacion = $Observacion;

        return $this;
    }

    /**
     * Get the value of Observacion.
     *
     * @return string
     */
    public function getObservacion()
    {
        return $this->Observacion;
    }

    /**
     * Set the value of Foto.
     *
     * @param string $Foto
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setFoto($Foto)
    {
        $this->Foto = $Foto;

        return $this;
    }

    /**
     * Get the value of Foto.
     *
     * @return string
     */
    public function getFoto()
    {
        return $this->Foto;
    }

    /**
     * Set the value of Usuario_id.
     *
     * @param integer $Usuario_id
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setUsuarioId($Usuario_id)
    {
        $this->Usuario_id = $Usuario_id;

        return $this;
    }

    /**
     * Get the value of Usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->Usuario_id;
    }

    /**
     * Add InsumoPersonal entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\InsumoPersonal $insumoPersonal
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function addInsumoPersonal(InsumoPersonal $insumoPersonal)
    {
        $this->insumoPersonals[] = $insumoPersonal;

        return $this;
    }

    /**
     * Remove InsumoPersonal entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\InsumoPersonal $insumoPersonal
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function removeInsumoPersonal(InsumoPersonal $insumoPersonal)
    {
        $this->insumoPersonals->removeElement($insumoPersonal);

        return $this;
    }

    /**
     * Get InsumoPersonal entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getInsumoPersonals()
    {
        return $this->insumoPersonals;
    }

    /**
     * Add Salon entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\Salon $salon
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function addSalon(Salon $salon)
    {
        $this->salons[] = $salon;

        return $this;
    }

    /**
     * Remove Salon entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\Salon $salon
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function removeSalon(Salon $salon)
    {
        $this->salons->removeElement($salon);

        return $this;
    }

    /**
     * Get Salon entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSalons()
    {
        return $this->salons;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Usuario $usuario
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Documento', 'Logros', 'Observacion', 'Foto', 'Usuario_id');
    }
}