<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-31 18:07:12.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Umg\EscuelaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Umg\EscuelaBundle\Entity\Salon
 *
 * @ORM\Entity()
 * @ORM\Table(name="Salon", indexes={@ORM\Index(name="fk_Salon_Personal1_idx", columns={"Personal_id"})})
 */
class Salon
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    protected $Nombre;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $Aula;

    /**
     * @ORM\Column(type="bigint")
     */
    protected $Personal_id;

    /**
     * @ORM\OneToMany(targetEntity="AlumnoSalon", mappedBy="salon")
     * @ORM\JoinColumn(name="id", referencedColumnName="Salon_id")
     */
    protected $alumnoSalons;

    /**
     * @ORM\ManyToOne(targetEntity="Personal", inversedBy="salons")
     * @ORM\JoinColumn(name="Personal_id", referencedColumnName="id")
     */
    protected $personal;

    public function __construct()
    {
        $this->alumnoSalons = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Aula.
     *
     * @param string $Aula
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function setAula($Aula)
    {
        $this->Aula = $Aula;

        return $this;
    }

    /**
     * Get the value of Aula.
     *
     * @return string
     */
    public function getAula()
    {
        return $this->Aula;
    }

    /**
     * Set the value of Personal_id.
     *
     * @param integer $Personal_id
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function setPersonalId($Personal_id)
    {
        $this->Personal_id = $Personal_id;

        return $this;
    }

    /**
     * Get the value of Personal_id.
     *
     * @return integer
     */
    public function getPersonalId()
    {
        return $this->Personal_id;
    }

    /**
     * Add AlumnoSalon entity to collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\AlumnoSalon $alumnoSalon
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function addAlumnoSalon(AlumnoSalon $alumnoSalon)
    {
        $this->alumnoSalons[] = $alumnoSalon;

        return $this;
    }

    /**
     * Remove AlumnoSalon entity from collection (one to many).
     *
     * @param \Umg\EscuelaBundle\Entity\AlumnoSalon $alumnoSalon
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function removeAlumnoSalon(AlumnoSalon $alumnoSalon)
    {
        $this->alumnoSalons->removeElement($alumnoSalon);

        return $this;
    }

    /**
     * Get AlumnoSalon entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAlumnoSalons()
    {
        return $this->alumnoSalons;
    }

    /**
     * Set Personal entity (many to one).
     *
     * @param \Umg\EscuelaBundle\Entity\Personal $personal
     * @return \Umg\EscuelaBundle\Entity\Salon
     */
    public function setPersonal(Personal $personal = null)
    {
        $this->personal = $personal;

        return $this;
    }

    /**
     * Get Personal entity (many to one).
     *
     * @return \Umg\EscuelaBundle\Entity\Personal
     */
    public function getPersonal()
    {
        return $this->personal;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Aula', 'Personal_id');
    }
}